### PR TITLE
Make the build parameters visible in the graph

### PR DESCRIPTION
**Pull request by pcardos**
This addresses issue #4

### CODE REVIEW

**Comment by pskumar448** [comment]
@pcardos 
At present this plugin is not visible in update center. 
Submitted PR for that https://github.com/jenkins-infra/backend-update-center2/pull/138

Once this PR merged.

**Comment by pcardos** [comment]
@pskumar448 

OK, please keep me posted, thanks.

**Comment by pskumar448** [comment]
Now the plugin is visible in update center.

**Comment by pskumar448** [comment]
Can you please attach a screenshot how it looks after showing the parameters in the graph.

**Comment by pcardos** [comment]
Sure, attachment below:

buildgraphchanges

**Comment by pcardos** [comment]
Sorry, I've accidentally closed it, re-opening ..

**Pull request merged**
