### PR TITLE
Do not conflict with prototype.js

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by roidelapluie** [comment]
@ndeloof any news on this?

**Comment by ndeloof** [comment]
I'm not actively maintaining this plugin, feel free to take ownership on it.

**Comment by roidelapluie** [comment]
I don't have enough development skills for maintaining this.

**Comment by cdenneen** [comment]
@ndeloof can this be merged?

**Comment by ndeloof** [comment]
I'm not actively maintaining this plugin, feel free to take ownership on it.

**Comment by pskumar448** [comment]
Verified.

**Pull request merged**
